services:
  mongo:
    image: mongo:latest
    container_name: magic_movies_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME:-magic-stream-movies}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"      # need to remove in production  
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - magic-network



volumes:
  mongo-data:

networks:
  magic-network:
    driver: bridge